[world]
kind = "WorldContract"
class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
original_class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x154f50b2e8a50397b1a71d5964d0a8f299ea821867a00365bb9cb8488601640"
seed = "rl_chess_contracts"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/mlv-rl-chess/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
class_hash = "0xebb3f6f5e1c76a796341d1a545a24cb66793c154c422939dba0649b64c17d4"
original_class_hash = "0xebb3f6f5e1c76a796341d1a545a24cb66793c154c422939dba0649b64c17d4"
base_class_hash = "0x0"
abi = "manifests/dev/deployment/abis/contracts/rl_chess_contracts-admin-264050f1.json"
reads = []
writes = ["rl_chess_contracts-GameFormat"]
init_calldata = []
tag = "rl_chess_contracts-admin"
systems = []
manifest_name = "rl_chess_contracts-admin-264050f1"

[[contracts]]
kind = "DojoContract"
class_hash = "0x59a2e479ec0229c981769c284c2e83d3107f5a8e6e749427979f48aea22f5bf"
original_class_hash = "0x59a2e479ec0229c981769c284c2e83d3107f5a8e6e749427979f48aea22f5bf"
base_class_hash = "0x0"
abi = "manifests/dev/deployment/abis/contracts/rl_chess_contracts-gameroom-2640d291.json"
reads = []
writes = [
    "rl_chess_contracts-Game",
    "rl_chess_contracts-GameFormat",
    "rl_chess_contracts-GameState",
    "rl_chess_contracts-GameSquares",
    "rl_chess_contracts-Player",
]
init_calldata = []
tag = "rl_chess_contracts-gameroom"
systems = [
    "start_game",
    "make_move",
]
manifest_name = "rl_chess_contracts-gameroom-2640d291"

[[contracts]]
kind = "DojoContract"
class_hash = "0x29aaf81a958b39202b81b4099d7956084983166e45c5d9ff4fcdb0299e747ee"
original_class_hash = "0x29aaf81a958b39202b81b4099d7956084983166e45c5d9ff4fcdb0299e747ee"
base_class_hash = "0x0"
abi = "manifests/dev/deployment/abis/contracts/rl_chess_contracts-lobby-5515fed8.json"
reads = []
writes = [
    "rl_chess_contracts-Game",
    "rl_chess_contracts-GameFormat",
    "rl_chess_contracts-GameState",
    "rl_chess_contracts-Player",
]
init_calldata = []
tag = "rl_chess_contracts-lobby"
systems = []
manifest_name = "rl_chess_contracts-lobby-5515fed8"

[[models]]
kind = "DojoModel"
class_hash = "0x7f536eb478cefcc4d398f2eac5cba8af3ae2d099400a87c840799dada88f9b2"
original_class_hash = "0x7f536eb478cefcc4d398f2eac5cba8af3ae2d099400a87c840799dada88f9b2"
abi = "manifests/dev/deployment/abis/models/rl_chess_contracts-Game-2f660bca.json"
tag = "rl_chess_contracts-Game"
manifest_name = "rl_chess_contracts-Game-2f660bca"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "game_format_id"
type = "u16"
key = false

[[models.members]]
name = "room_owner_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "invitee_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "invite_state"
type = "InviteState"
key = false

[[models.members]]
name = "invite_expiry"
type = "u64"
key = false

[[models.members]]
name = "result"
type = "u8"
key = false

[[models.members]]
name = "winner"
type = "ContractAddress"
key = false

[[models.members]]
name = "room_start"
type = "u64"
key = false

[[models.members]]
name = "room_end"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x439e45f3eac03d7592d754c516f6148d850805a3b6804bd2ad7dc7e44985356"
original_class_hash = "0x439e45f3eac03d7592d754c516f6148d850805a3b6804bd2ad7dc7e44985356"
abi = "manifests/dev/deployment/abis/models/rl_chess_contracts-GameFormat-1a210de8.json"
tag = "rl_chess_contracts-GameFormat"
manifest_name = "rl_chess_contracts-GameFormat-1a210de8"

[[models.members]]
name = "game_format_id"
type = "u16"
key = true

[[models.members]]
name = "description"
type = "felt252"
key = false

[[models.members]]
name = "turn_expiry"
type = "u64"
key = false

[[models.members]]
name = "total_time_per_side"
type = "u64"
key = false

[[models.members]]
name = "total_time_string"
type = "felt252"
key = false

[[models.members]]
name = "increment"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x712b9ecc87d0c1c506ccbc572edc4f20969a95eb14aa911d73dc80d4b6d6597"
original_class_hash = "0x712b9ecc87d0c1c506ccbc572edc4f20969a95eb14aa911d73dc80d4b6d6597"
abi = "manifests/dev/deployment/abis/models/rl_chess_contracts-GameSquares-5c431eda.json"
tag = "rl_chess_contracts-GameSquares"
manifest_name = "rl_chess_contracts-GameSquares-5c431eda"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "x"
type = "u8"
key = true

[[models.members]]
name = "y"
type = "u8"
key = true

[[models.members]]
name = "piece"
type = "Piece"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5fd277528e3980fd742ea2c94825d69e74ace7db2bac325525b3ba11a6bed62"
original_class_hash = "0x5fd277528e3980fd742ea2c94825d69e74ace7db2bac325525b3ba11a6bed62"
abi = "manifests/dev/deployment/abis/models/rl_chess_contracts-GameState-28b58a4f.json"
tag = "rl_chess_contracts-GameState"
manifest_name = "rl_chess_contracts-GameState-28b58a4f"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "white"
type = "u8"
key = false

[[models.members]]
name = "turn"
type = "u32"
key = false

[[models.members]]
name = "turn_color"
type = "Color"
key = false

[[models.members]]
name = "w_turn_expiry_time"
type = "u64"
key = false

[[models.members]]
name = "b_turn_expiry_time"
type = "u64"
key = false

[[models.members]]
name = "w_total_time_left"
type = "u64"
key = false

[[models.members]]
name = "b_total_time_left"
type = "u64"
key = false

[[models.members]]
name = "game_start"
type = "u64"
key = false

[[models.members]]
name = "last_move_time"
type = "u64"
key = false

[[models.members]]
name = "game_end"
type = "u64"
key = false

[[models.members]]
name = "whitekingside"
type = "bool"
key = false

[[models.members]]
name = "whitequeenside"
type = "bool"
key = false

[[models.members]]
name = "blackkingside"
type = "bool"
key = false

[[models.members]]
name = "blackqueenside"
type = "bool"
key = false

[[models.members]]
name = "halfmove_clock"
type = "u16"
key = false

[[models.members]]
name = "en_passant_target_x"
type = "u8"
key = false

[[models.members]]
name = "en_passant_target_y"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4924922a31f97292ec92244afaaed70f9a343543d8f9b39a83461ca06bdf33d"
original_class_hash = "0x4924922a31f97292ec92244afaaed70f9a343543d8f9b39a83461ca06bdf33d"
abi = "manifests/dev/deployment/abis/models/rl_chess_contracts-Player-40fe735b.json"
tag = "rl_chess_contracts-Player"
manifest_name = "rl_chess_contracts-Player-40fe735b"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "profile_pic_type"
type = "ProfilePicType"
key = false

[[models.members]]
name = "profile_pic_uri"
type = "ByteArray"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false
