[world]
kind = "WorldContract"
class_hash = "0x2178527e9556d1aa21d3c2961d28f9114fcfed81b4c3674ed591c50ce46cc9d"
original_class_hash = "0x2178527e9556d1aa21d3c2961d28f9114fcfed81b4c3674ed591c50ce46cc9d"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x62540c14ee905c20b8f3d078fabe3dffb9712259b23290146be583edb8678aa"
transaction_hash = "0x4f05d448c2e9b1bb6ad0b69ecc7fc8ba3baa661340276929abef01012f42f95"
block_number = 3
seed = "dojo_rl_chess"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x4e27bbbb91d74b5bdda813858e37ad3b1ccbf4e9f82e9a6c33523e291ef9b73"
class_hash = "0x61b33af9f66f58ee5d2b6f8e763aac42dc15bc5a996766813f01785a6c158a5"
original_class_hash = "0x61b33af9f66f58ee5d2b6f8e763aac42dc15bc5a996766813f01785a6c158a5"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/rl_chess_contracts-admin-264050f1.json"
reads = []
writes = ["rl_chess_contracts-GameFormat"]
computed = []
init_calldata = []
tag = "rl_chess_contracts-admin"
manifest_name = "rl_chess_contracts-admin-264050f1"

[[contracts]]
kind = "DojoContract"
address = "0x56f90d3b9b83798f6125d8b3c348cd3651976f45c11b4369bc7cb78c53f8c8b"
class_hash = "0xf33b8a5ee2be2b670aba64442042e0f766ddeaa13b9f1526ad642deb767783"
original_class_hash = "0xf33b8a5ee2be2b670aba64442042e0f766ddeaa13b9f1526ad642deb767783"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/rl_chess_contracts-gameroom-2640d291.json"
reads = []
writes = [
    "rl_chess_contracts-Game",
    "rl_chess_contracts-GameFormat",
    "rl_chess_contracts-GameState",
    "rl_chess_contracts-Player",
]
computed = []
init_calldata = []
tag = "rl_chess_contracts-gameroom"
manifest_name = "rl_chess_contracts-gameroom-2640d291"

[[contracts]]
kind = "DojoContract"
address = "0x49eeb5cefd6336ffccfecd9bbf218158fb0f1740999ef5a07b5045991f6ac41"
class_hash = "0x3aa520c5100723d435d9a6ba94b8fe39582b60b1dc9e8922b77a541f9ccb25f"
original_class_hash = "0x3aa520c5100723d435d9a6ba94b8fe39582b60b1dc9e8922b77a541f9ccb25f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/rl_chess_contracts-lobby-5515fed8.json"
reads = []
writes = [
    "rl_chess_contracts-Game",
    "rl_chess_contracts-GameFormat",
    "rl_chess_contracts-GameState",
    "rl_chess_contracts-Player",
]
computed = []
init_calldata = []
tag = "rl_chess_contracts-lobby"
manifest_name = "rl_chess_contracts-lobby-5515fed8"

[[models]]
kind = "DojoModel"
class_hash = "0x3651a13464d8c028fd42ab593eb4e474b5d6d113d9f1fb2d1020a900fb18ee"
original_class_hash = "0x3651a13464d8c028fd42ab593eb4e474b5d6d113d9f1fb2d1020a900fb18ee"
abi = "manifests/dev/deployment/abis/models/rl_chess_contracts-Game-2f660bca.json"
tag = "rl_chess_contracts-Game"
manifest_name = "rl_chess_contracts-Game-2f660bca"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "game_format_id"
type = "u16"
key = false

[[models.members]]
name = "room_owner_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "invitee_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "invite_state"
type = "InviteState"
key = false

[[models.members]]
name = "invite_expiry"
type = "u64"
key = false

[[models.members]]
name = "result"
type = "u8"
key = false

[[models.members]]
name = "winner"
type = "ContractAddress"
key = false

[[models.members]]
name = "room_start"
type = "u64"
key = false

[[models.members]]
name = "room_end"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x77b1fde203add2f3be20d09c4edff53936c575cb04f60ac7470be12a2bcc909"
original_class_hash = "0x77b1fde203add2f3be20d09c4edff53936c575cb04f60ac7470be12a2bcc909"
abi = "manifests/dev/deployment/abis/models/rl_chess_contracts-GameFormat-1a210de8.json"
tag = "rl_chess_contracts-GameFormat"
manifest_name = "rl_chess_contracts-GameFormat-1a210de8"

[[models.members]]
name = "game_format_id"
type = "u16"
key = true

[[models.members]]
name = "description"
type = "felt252"
key = false

[[models.members]]
name = "turn_expiry"
type = "u64"
key = false

[[models.members]]
name = "total_time_per_side"
type = "u64"
key = false

[[models.members]]
name = "total_time_string"
type = "felt252"
key = false

[[models.members]]
name = "increment"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7d2490a0d4ff63d6cc602a92734f6543789a6fb826ac1924fad76c4a40cafbb"
original_class_hash = "0x7d2490a0d4ff63d6cc602a92734f6543789a6fb826ac1924fad76c4a40cafbb"
abi = "manifests/dev/deployment/abis/models/rl_chess_contracts-GameSquares-5c431eda.json"
tag = "rl_chess_contracts-GameSquares"
manifest_name = "rl_chess_contracts-GameSquares-5c431eda"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "x"
type = "u8"
key = true

[[models.members]]
name = "y"
type = "u8"
key = true

[[models.members]]
name = "piece"
type = "Piece"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6c3d9f8eca1c791b2f2250355c35831451e2422ca1ff1004d3b364ac17c481"
original_class_hash = "0x6c3d9f8eca1c791b2f2250355c35831451e2422ca1ff1004d3b364ac17c481"
abi = "manifests/dev/deployment/abis/models/rl_chess_contracts-GameState-28b58a4f.json"
tag = "rl_chess_contracts-GameState"
manifest_name = "rl_chess_contracts-GameState-28b58a4f"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "white"
type = "u8"
key = false

[[models.members]]
name = "turn"
type = "u32"
key = false

[[models.members]]
name = "turn_color"
type = "Color"
key = false

[[models.members]]
name = "w_turn_expiry_time"
type = "u64"
key = false

[[models.members]]
name = "b_turn_expiry_time"
type = "u64"
key = false

[[models.members]]
name = "w_total_time_left"
type = "u64"
key = false

[[models.members]]
name = "b_total_time_left"
type = "u64"
key = false

[[models.members]]
name = "game_start"
type = "u64"
key = false

[[models.members]]
name = "last_move_time"
type = "u64"
key = false

[[models.members]]
name = "game_end"
type = "u64"
key = false

[[models.members]]
name = "whitekingside"
type = "bool"
key = false

[[models.members]]
name = "whitequeenside"
type = "bool"
key = false

[[models.members]]
name = "blackkingside"
type = "bool"
key = false

[[models.members]]
name = "blackqueenside"
type = "bool"
key = false

[[models.members]]
name = "halfmove_clock"
type = "u16"
key = false

[[models.members]]
name = "en_passant_target_x"
type = "u8"
key = false

[[models.members]]
name = "en_passant_target_y"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x44ca612a73c1a9b146f54a1755eb2a53db5887854b0af807b3c4ebe173448d7"
original_class_hash = "0x44ca612a73c1a9b146f54a1755eb2a53db5887854b0af807b3c4ebe173448d7"
abi = "manifests/dev/deployment/abis/models/rl_chess_contracts-Player-40fe735b.json"
tag = "rl_chess_contracts-Player"
manifest_name = "rl_chess_contracts-Player-40fe735b"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "profile_pic_type"
type = "ProfilePicType"
key = false

[[models.members]]
name = "profile_pic_uri"
type = "ByteArray"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false
