kind = "DojoContract"
class_hash = "0x1a903be1ebb04883e8f8b6d7304176a45441005c1b03fc2a65a96c4731663c3"
original_class_hash = "0x1a903be1ebb04883e8f8b6d7304176a45441005c1b03fc2a65a96c4731663c3"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/rl_chess_contracts-lobby-5515fed8.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "rl_chess_contracts-lobby"
manifest_name = "rl_chess_contracts-lobby-5515fed8"
