kind = "DojoContract"
class_hash = "0x3aa520c5100723d435d9a6ba94b8fe39582b60b1dc9e8922b77a541f9ccb25f"
original_class_hash = "0x3aa520c5100723d435d9a6ba94b8fe39582b60b1dc9e8922b77a541f9ccb25f"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/rl_chess_contracts-lobby-5515fed8.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "rl_chess_contracts-lobby"
manifest_name = "rl_chess_contracts-lobby-5515fed8"
