kind = "DojoContract"
class_hash = "0xebb3f6f5e1c76a796341d1a545a24cb66793c154c422939dba0649b64c17d4"
original_class_hash = "0xebb3f6f5e1c76a796341d1a545a24cb66793c154c422939dba0649b64c17d4"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/rl_chess_contracts-admin-264050f1.json"
reads = []
writes = []
init_calldata = []
tag = "rl_chess_contracts-admin"
systems = []
manifest_name = "rl_chess_contracts-admin-264050f1"
