kind = "DojoContract"
class_hash = "0x59a2e479ec0229c981769c284c2e83d3107f5a8e6e749427979f48aea22f5bf"
original_class_hash = "0x59a2e479ec0229c981769c284c2e83d3107f5a8e6e749427979f48aea22f5bf"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/rl_chess_contracts-gameroom-2640d291.json"
reads = []
writes = []
init_calldata = []
tag = "rl_chess_contracts-gameroom"
systems = [
    "start_game",
    "make_move",
]
manifest_name = "rl_chess_contracts-gameroom-2640d291"
