# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x05types\"1\n\nEnumOption\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\x02ty\x18\x02 \x01(\x0b\x32\t.types.Ty\"H\n\x04\x45num\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06option\x18\x02 \x01(\r\x12\"\n\x07options\x18\x03 \x03(\x0b\x32\x11.types.EnumOption\"L\n\tPrimitive\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.types.PrimitiveType\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.types.Value\"7\n\x06Struct\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1f\n\x08\x63hildren\x18\x02 \x03(\x0b\x32\r.types.Member\"$\n\x05\x41rray\x12\x1b\n\x08\x63hildren\x18\x01 \x03(\x0b\x32\t.types.Ty\"\xc7\x01\n\x02Ty\x12%\n\tprimitive\x18\x02 \x01(\x0b\x32\x10.types.PrimitiveH\x00\x12\x1b\n\x04\x65num\x18\x03 \x01(\x0b\x32\x0b.types.EnumH\x00\x12\x1f\n\x06struct\x18\x04 \x01(\x0b\x32\r.types.StructH\x00\x12\x1d\n\x05tuple\x18\x05 \x01(\x0b\x32\x0c.types.ArrayH\x00\x12\x1d\n\x05\x61rray\x18\x06 \x01(\x0b\x32\x0c.types.ArrayH\x00\x12\x13\n\tbytearray\x18\x07 \x01(\tH\x00\x42\t\n\x07ty_type\":\n\x06Member\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\x02ty\x18\x02 \x01(\x0b\x32\t.types.Ty\x12\x0b\n\x03key\x18\x03 \x01(\x08\"\x84\x01\n\x05Value\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x12\x14\n\nuint_value\x18\x04 \x01(\x04H\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x12\x14\n\nbyte_value\x18\x06 \x01(\x0cH\x00\x42\x0c\n\nvalue_type*\xbb\x01\n\rPrimitiveType\x12\x06\n\x02U8\x10\x00\x12\x07\n\x03U16\x10\x01\x12\x07\n\x03U32\x10\x02\x12\x07\n\x03U64\x10\x03\x12\x08\n\x04U128\x10\x04\x12\x08\n\x04U256\x10\x05\x12\t\n\x05USIZE\x10\x06\x12\x08\n\x04\x42OOL\x10\x07\x12\x0b\n\x07\x46\x45LT252\x10\x08\x12\x0e\n\nCLASS_HASH\x10\t\x12\x14\n\x10\x43ONTRACT_ADDRESS\x10\n\x12\x06\n\x02I8\x10\x0b\x12\x07\n\x03I16\x10\x0c\x12\x07\n\x03I32\x10\r\x12\x07\n\x03I64\x10\x0e\x12\x08\n\x04I128\x10\x0f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRIMITIVETYPE']._serialized_start=719
  _globals['_PRIMITIVETYPE']._serialized_end=906
  _globals['_ENUMOPTION']._serialized_start=23
  _globals['_ENUMOPTION']._serialized_end=72
  _globals['_ENUM']._serialized_start=74
  _globals['_ENUM']._serialized_end=146
  _globals['_PRIMITIVE']._serialized_start=148
  _globals['_PRIMITIVE']._serialized_end=224
  _globals['_STRUCT']._serialized_start=226
  _globals['_STRUCT']._serialized_end=281
  _globals['_ARRAY']._serialized_start=283
  _globals['_ARRAY']._serialized_end=319
  _globals['_TY']._serialized_start=322
  _globals['_TY']._serialized_end=521
  _globals['_MEMBER']._serialized_start=523
  _globals['_MEMBER']._serialized_end=581
  _globals['_VALUE']._serialized_start=584
  _globals['_VALUE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
