[world]
name = "rl_chess_contracts"
description = "A fully onchain Chess to demonstrate RL in Chess"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "rl_chess_contracts"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/rl_chess_contracts"
telegram = "https://t.me/dojoengine"

[namespace]
default = "rl_chess_contracts"

[env]
rpc_url = "https://api.cartridge.gg/x/mlv-rl-chess/katana"
# RPC: http://slot.prod.svc.cluster.local/x/mlv-rl-chess/katana
account_address = "0x6154d94660e5fd6becfec6e87d320cdc1c8956b724c01f469b4d384c17e9c98"
private_key = "0x343c146f7e08016b137ecc5fcd0f25e009dc056d5ce5b0731b9d20edb6784df"
world_address = "0x154f50b2e8a50397b1a71d5964d0a8f299ea821867a00365bb9cb8488601640" 

# Endpoints:
#   GRAPHQL: https://api.cartridge.gg/x/mlv-rl-chess/torii/graphql
#   GRPC: https://api.cartridge.gg/x/mlv-rl-chess/torii
