kind = "DojoModel"
class_hash = "0x439e45f3eac03d7592d754c516f6148d850805a3b6804bd2ad7dc7e44985356"
original_class_hash = "0x439e45f3eac03d7592d754c516f6148d850805a3b6804bd2ad7dc7e44985356"
abi = "manifests/dev/base/abis/models/rl_chess_contracts-GameFormat-1a210de8.json"
tag = "rl_chess_contracts-GameFormat"
manifest_name = "rl_chess_contracts-GameFormat-1a210de8"

[[members]]
name = "game_format_id"
type = "u16"
key = true

[[members]]
name = "description"
type = "felt252"
key = false

[[members]]
name = "turn_expiry"
type = "u64"
key = false

[[members]]
name = "total_time_per_side"
type = "u64"
key = false

[[members]]
name = "total_time_string"
type = "felt252"
key = false

[[members]]
name = "increment"
type = "u8"
key = false
