kind = "DojoModel"
class_hash = "0x4924922a31f97292ec92244afaaed70f9a343543d8f9b39a83461ca06bdf33d"
original_class_hash = "0x4924922a31f97292ec92244afaaed70f9a343543d8f9b39a83461ca06bdf33d"
abi = "manifests/dev/base/abis/models/rl_chess_contracts-Player-40fe735b.json"
tag = "rl_chess_contracts-Player"
manifest_name = "rl_chess_contracts-Player-40fe735b"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "profile_pic_type"
type = "ProfilePicType"
key = false

[[members]]
name = "profile_pic_uri"
type = "ByteArray"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
