kind = "DojoModel"
class_hash = "0x7f536eb478cefcc4d398f2eac5cba8af3ae2d099400a87c840799dada88f9b2"
original_class_hash = "0x7f536eb478cefcc4d398f2eac5cba8af3ae2d099400a87c840799dada88f9b2"
abi = "manifests/dev/base/abis/models/rl_chess_contracts-Game-2f660bca.json"
tag = "rl_chess_contracts-Game"
manifest_name = "rl_chess_contracts-Game-2f660bca"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "game_format_id"
type = "u16"
key = false

[[members]]
name = "room_owner_address"
type = "ContractAddress"
key = false

[[members]]
name = "invitee_address"
type = "ContractAddress"
key = false

[[members]]
name = "invite_state"
type = "InviteState"
key = false

[[members]]
name = "invite_expiry"
type = "u64"
key = false

[[members]]
name = "result"
type = "u8"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false

[[members]]
name = "room_start"
type = "u64"
key = false

[[members]]
name = "room_end"
type = "u64"
key = false
