kind = "DojoModel"
class_hash = "0x5fd277528e3980fd742ea2c94825d69e74ace7db2bac325525b3ba11a6bed62"
original_class_hash = "0x5fd277528e3980fd742ea2c94825d69e74ace7db2bac325525b3ba11a6bed62"
abi = "manifests/dev/base/abis/models/rl_chess_contracts-GameState-28b58a4f.json"
tag = "rl_chess_contracts-GameState"
manifest_name = "rl_chess_contracts-GameState-28b58a4f"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "white"
type = "u8"
key = false

[[members]]
name = "turn"
type = "u32"
key = false

[[members]]
name = "turn_color"
type = "Color"
key = false

[[members]]
name = "w_turn_expiry_time"
type = "u64"
key = false

[[members]]
name = "b_turn_expiry_time"
type = "u64"
key = false

[[members]]
name = "w_total_time_left"
type = "u64"
key = false

[[members]]
name = "b_total_time_left"
type = "u64"
key = false

[[members]]
name = "game_start"
type = "u64"
key = false

[[members]]
name = "last_move_time"
type = "u64"
key = false

[[members]]
name = "game_end"
type = "u64"
key = false

[[members]]
name = "whitekingside"
type = "bool"
key = false

[[members]]
name = "whitequeenside"
type = "bool"
key = false

[[members]]
name = "blackkingside"
type = "bool"
key = false

[[members]]
name = "blackqueenside"
type = "bool"
key = false

[[members]]
name = "halfmove_clock"
type = "u16"
key = false

[[members]]
name = "en_passant_target_x"
type = "u8"
key = false

[[members]]
name = "en_passant_target_y"
type = "u8"
key = false
